# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Chocolates',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreI', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proporcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Chocolate')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Ingrediente')),
            ],
        ),
    ]
